version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7348:8000"
    depends_on:
      - rabbitmq
      - auth
    environment:
      - POETRY_VIRTUALENVS_CREATE=false

  storage-manager:
    build:
      context: ./kaggle-storage-manager
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
      - meilisearch
      - mongodb
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
      - MEILISERCH_MASTER_KEY=${MEILISERCH_MASTER_KEY}

  analyzer:
    build:
      context: ./analyzer
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    depends_on:
      - rabbitmq
      - auth
      - storage-manager
    environment:
      - POETRY_VIRTUALENVS_CREATE=false

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POETRY_VIRTUALENVS_CREATE=false
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-guest}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-guest}

  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data
    environment:
      - MEILI_MASTER_KEY=${MEILISERCH_MASTER_KEY}

  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_ROOT_USER:-root}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}

volumes:
  meili_data:
