[tool.poetry]
name = "kaggle Analyzer"
version = "0.0.1"
description = "Insert any link and analyze kaggle dataset."
license = "MIT"
authors = ["bani2016up@gmail.com", "dkparfenov@hse.ru"]
maintainers = ["bani2016up@gmail.com", "dkparfenov@hse.ru"]
readme = "README.md"
homepage = "https://github.com/bani2016up/kaggle-analyzer.gite"
repository = "https://github.com/bani2016up/kaggle-analyzer.gite"
documentation = "https://github.com/bani2016up/kaggle-analyzer.gite"
dataset = "https://www.kaggle.com/datasets/ismetsemedov/transactions"
classifiers = [
    "Development Status :: 1 - Beta",
    "Environment :: Web Environment",
    "Framework :: FastAPI",
    "Framework :: Streamlit",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.12"
]
packages = [{ include = "kaggle_Analyzer" }]

[tool.poetry.dependencies]
python = "^3.12"
FastAPI = "^3.2 || ^4.0 || ^5.0"

[tool.poetry.group.dev.dependencies]
black = "*"
mypy = "*"
pre-commit = "*"
ruff = "*"
kaggle = "1.6.17"

# [tool.poetry.group.test.dependencies]
# coverage = "*"
# pytest = "*"
# pytest-cov = "*"
# pytest-django = "*"
# tox = "*"

[tool.poetry.extras]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
